---
spring:
  profiles: profile1
test:
  message: config-server-1

---
spring:
  profiles: profile2
test:
  message: config-server-1


---
spring:
  profiles: profile3
test:
  message: config-server-1
